#!/usr/bin/env python3
"""
Author : denton <denton@localhost>
Date   : 2020-09-13
Purpose: save current folder to ~/.dydir
"""

# --------------------------------------------------
def main():
    """Make a jazz noise here"""
    import os

    path = os.getenv("HOME")
    f1 = open(path + "/.dydir","a+")
    cwd = os.getcwd()
    f1.write(cwd + "\n")
    f1.close



# --------------------------------------------------
if __name__ == '__main__':
    main()
